CCS Analysis

Comparison of carbon capture and storage (CCS) pathways for California under scenario 1 (coordinated) and scenario 2 (uncoordianted)


SETUP

In [1]:
import networkx as nx
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import hashlib
import world_2_edits as w2
import world_1_s1_edits as w1_1
import world_1_s2_edits as w1_2

In [2]:
import importlib
importlib.reload(w1_1)
importlib.reload(w1_2)
importlib.reload(w2)

MONTE-CARLO FOR W1.1 (Organized Chaos)

In [3]:
sim1_1 = w1_1.monte_carlo(1000, sampling = True)

df1_1 = pd.DataFrame(sim1_1)
df1_1.head()

projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC3   definition  delay=   0.0 prob=0.050
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110

,c_abandon,rep,num_cap,n_c_abandoned,completion,final volume
0,"{'projC1': 'approval', 'projC4': 'approval'}",0,4,2,127.0,3.5
1,{'projC1': 'definition'},1,4,1,127.0,5.0
2,"{'projC3': 'approval', 'projC4': 'approval'}",2,4,2,127.0,3.0
3,{'projC3': 'approval'},3,4,1,127.0,4.5
4,{},4,4,0,127.0,6.5

In [4]:
df1_1.describe()

               rep  num_cap  n_c_abandoned   completion  final volume
count  1000.000000   1000.0    1000.000000  1000.000000   1000.000000
mean    499.500000      4.0       0.603000   126.908000      5.533500
std     288.819436      0.0       0.721048     1.051019      1.167901
min       0.000000      4.0       0.000000   105.000000      0.000000
25%     249.750000      4.0       0.000000   127.000000      5.000000
50%     499.500000      4.0       0.000000   127.000000      6.500000
75%     749.250000      4.0       1.000000   127.000000      6.500000
max     999.000000      4.0       4.000000   127.000000      6.500000

MONTE CARLO FOR W1.2 (BUILD IT AND THEY WILL COME)

In [5]:
sim1_2 = w1_1.monte_carlo(1000, sampling = True)

df1_2 = pd.DataFrame(sim1_2)
df1_2.head()

projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC3   definition  delay=   0.0 prob=0.050
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110
projC2   definition  delay=   0.0 prob=0.050
projC2   approval    delay=  38.0 prob=0.110
projC3   definition  delay=   0.0 prob=0.050
projC3   approval    delay=  28.0 prob=0.090
projC4   definition  delay=   0.0 prob=0.050
projC4   approval    delay=  31.0 prob=0.095
projC1   definition  delay=   0.0 prob=0.050
projC1   approval    delay=  38.0 prob=0.110

,c_abandon,rep,num_cap,n_c_abandoned,completion,final volume
0,"{'projC1': 'approval', 'projC4': 'approval'}",0,4,2,127.0,3.5
1,{'projC1': 'definition'},1,4,1,127.0,5.0
2,"{'projC3': 'approval', 'projC4': 'approval'}",2,4,2,127.0,3.0
3,{'projC3': 'approval'},3,4,1,127.0,4.5
4,{},4,4,0,127.0,6.5

In [6]:
df1_2.describe()

               rep  num_cap  n_c_abandoned   completion  final volume
count  1000.000000   1000.0    1000.000000  1000.000000   1000.000000
mean    499.500000      4.0       0.603000   126.908000      5.533500
std     288.819436      0.0       0.721048     1.051019      1.167901
min       0.000000      4.0       0.000000   105.000000      0.000000
25%     249.750000      4.0       0.000000   127.000000      5.000000
50%     499.500000      4.0       0.000000   127.000000      6.500000
75%     749.250000      4.0       1.000000   127.000000      6.500000
max     999.000000      4.0       4.000000   127.000000      6.500000

MONTE-CARLO FOR S2

In [7]:
sim2 = w2.monte_carlo(1000, sampling = True)

df2 = pd.DataFrame(sim2)
df2.head()

,a_c,a_t,a_s,rep,num_stor,storage abandoned,num_trans,transport abandoned,num_cap,capture abandoned,completion,final volume
0,"{'projC1': 'definition joint node', 'projC2': ...","{'projT2': 'definition joint node', 'projT3': ...",{'projS1': 'FID joint node'},0,1,1,3,3,4,4,0.0,0.0
1,"{'projC1': 'definition joint node', 'projC2': ...","{'projT2': 'definition joint node', 'projT1': ...",{'projS1': 'FID joint node'},1,1,1,3,3,4,4,0.0,0.0
2,"{'projC3': 'definition joint node', 'projC1': ...","{'projT1': 'definition joint node', 'projT2': ...",{'projS1': 'FID joint node'},2,1,1,3,3,4,4,0.0,0.0
3,"{'projC3': 'definition joint node', 'projC1': ...","{'projT1': 'definition joint node', 'projT2': ...",{'projS1': 'FID joint node'},3,1,1,3,3,4,4,0.0,0.0
4,"{'projC4': 'definition joint node', 'projC1': ...","{'projT3': 'definition joint node', 'projT2': ...",{'projS1': 'FID joint node'},4,1,1,3,3,4,4,0.0,0.0

In [8]:
df2.describe()

,rep,num_stor,storage abandoned,num_trans,transport abandoned,num_cap,capture abandoned,completion,final volume
count,1000.000000,1000.0,1000.000000,1000.0,1000.000000,1000.0,1000.000000,1000.000000,1000.000000
mean,499.500000,1.0,0.714000,3.0,2.266000,4.0,2.980000,11.803000,1.673000
std,288.819436,0.0,0.452115,0.0,1.190236,0.0,1.634096,18.794878,2.674458
min,0.000000,1.0,0.000000,3.0,0.000000,4.0,0.000000,0.000000,0.000000
25%,249.750000,1.0,0.000000,3.0,1.000000,4.0,1.000000,0.000000,0.000000
50%,499.500000,1.0,1.000000,3.0,3.000000,4.0,4.000000,0.000000,0.000000
75%,749.250000,1.0,1.000000,3.0,3.000000,4.0,4.000000,36.000000,5.000000
max,999.000000,1.0,1.000000,3.0,3.000000,4.0,4.000000,63.000000,6.500000